verbose: false
instrumentation:
    preserve-comments: true
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['test/*.js']
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [95, 99]
        lines: [95, 99]
        functions: [95, 99]
        branches: [95, 99]
