# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  node-6:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: uname -a
      - run: node --version
      - run: npm --version
      - run: yarn install
      - run: yarn lint
      - run: yarn clean
      - run: yarn test
      - run: yarn browser
      - run: yarn report
  node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: uname -a
      - run: node --version
      - run: npm --version
      - run: yarn install
      - run: yarn lint
      - run: yarn clean
      - run: yarn test
      - run: yarn browser
      - run: yarn report

workflows:
  version: 2
  build_and_test:
    jobs:
      - node-6
      - node-8
